[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = [
  'yarn lint --fix',  # Run ESLint fix
  'yarn build'        # Build the application
]

[start]
cmd = 'node .next/standalone/server.js'

[variables]
NODE_ENV = 'production'
PORT = '3000' 